login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'

urlpatterns = [
             url(r'^$', views.home, name="home"),
             url(r'^login/$', views.login_view, name="login"),
             url(r'^logout/$', views.logout_view, name="logout"),
             ]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    # Vista para pagina de inicio

    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/', include('login.urls')),
  ]

login/models.py
from django.db import models

# Create your models here.
class Usuario(models.Model):
    Nombre = models.CharField(max_length=35)
    Apellido = models.CharField(max_length=35)
    Email = models.CharField(max_length=35)
    Codigo = models.CharField(max_length=8)

    def NombreCompleto(self):
        cadena="{0} {1}"
        return cadena.format(self.Nombre, self.Apellido)
    @property
    def __str__(self):
        return self.NombreCompleto()

login/views.py
from django.shortcuts import render

def home(request):
    """
    Página Inicial.

    """
    return render(request,'login.html')


def login_view(request):
    """
    Página de Login.
    """
    next_url = ''
    if request.GET:
        next_url = request.GET.get('next', '')

    if not request.user.is_authenticated:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('passsword')
            exist = User.objects.filter(username=username).exists()
            user = authenticate(username=username, password=password)

            if exist:
                if user is not None:
                    if user.is_active:
                        login(request, user)
                        if next_url:
                            return redirect(next_url)
                        else:
                            return redirect('login:home')
                    else:
                        messages.add_message(request, messages.WARNING,
                                             'Usuario -%s- existe pero no está activo.' % username)
                else:
                    messages.add_message(request, messages.ERROR, 'Credenciales incorrectos.')
            else:
                messages.add_message(request, messages.ERROR, 'Usuario -%s- no existe.' % username)
        return render(request, 'login.html', {'next': next_url})
    else:
        if next_url:
            return redirect(next_url)
        else:
            return redirect('login:home')


def logout_view(request):
    """
        Cierra sesión de usuario.
    """
    logout(request)
    return redirect('login:home')

login/templates/login.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>

    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">

    <link href="{% static "css/login.css" %}" rel="stylesheet">
</head>
<body>

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <h1 class="text-left">{{ message }}</h1><br/>
                    {% endfor %}
                </ul>
            {% else %}
                <h1 class="text-center">Bienvenido</h1>
            {% endif %}
        </div>
        <form accept-charset="UTF-8" role="form" action="{% url 'login:login' %}{% if next %}?next={{next}}{% endif %}" method="post"> {% csrf_token %}
            <div class="modal-body">
                <div class="form-group">
                    <input type="text" name="username" class="form-control input-lg" placeholder="Usuario"
                           ip="username"/>
                </div>

                <div class="form-group">
                    <input type="password" name="passsword" class="form-control input-lg" placeholder="Contraseña"
                           id="password"/>
                </div>

            </div>
        </form>
    </div>
</div>
</body>

login/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>